# Generated by Django 4.1.4 on 2023-07-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0007_alter_production_actual_working_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='mile_run_end_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='mile_run_start_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
