# Generated by Django 4.1.4 on 2023-07-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0012_production_pd_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseJobType',
            fields=[
                ('base_job_type_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('base_job_type_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'base_job_type',
            },
        ),
    ]
