# Generated by Django 4.1.4 on 2023-07-31 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0018_alter_weight_time_in_alter_weight_time_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTimeEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('mill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basemill')),
            ],
            options={
                'db_table': 'base_time_estimate',
            },
        ),
    ]
