# Generated by Django 4.1.4 on 2023-08-09 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0030_weight_stone_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='stone_type',
            new_name='stone_type_name',
        ),
    ]
