# Generated by Django 4.1.4 on 2023-08-09 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weightapp', '0034_alter_weight_amount_alter_weight_amount_vat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighthistory',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update', to=settings.AUTH_USER_MODEL),
        ),
    ]
