# Generated by Django 4.1.4 on 2023-08-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0037_basecustomer_weight_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCarRegistration',
            fields=[
                ('car_registration_id', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='รหัสทะเบียนรถ')),
                ('car_registration_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อทะเบียนรถ')),
                ('car_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='ประเภทรถ')),
            ],
            options={
                'verbose_name': 'ทะเบียนรถ',
                'verbose_name_plural': 'ข้อมูลทะเบียนรถ',
                'db_table': 'base_car_registration',
            },
        ),
    ]
