# Generated by Django 4.1.4 on 2023-08-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0041_basecarrytype_basetransport'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCarTeam',
            fields=[
                ('car_team_id', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='รหัสทีม')),
                ('car_team_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อทีม')),
            ],
            options={
                'verbose_name': 'ทีม',
                'verbose_name_plural': 'ข้อมูลทีม',
                'db_table': 'base_car_team',
            },
        ),
        migrations.CreateModel(
            name='BaseCar',
            fields=[
                ('car_id', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='รหัสรถร่วม')),
                ('car_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อรถร่วม')),
                ('base_car_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecarteam', verbose_name='ทีม')),
            ],
            options={
                'verbose_name': 'รถร่วม',
                'verbose_name_plural': 'ข้อมูลรถร่วม',
                'db_table': 'base_car',
            },
        ),
    ]
