# Generated by Django 4.1.4 on 2023-08-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0043_alter_basecar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecustomer',
            name='is_stone_estimate',
            field=models.BooleanField(default=False, verbose_name='ใช้ในการประมาณการณ์หิน'),
        ),
    ]
