# Generated by Django 4.1.4 on 2023-09-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0048_rename_id_basemill_mill_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='fertilizer',
            new_name='fertilizer_name',
        ),
        migrations.RenameField(
            model_name='weighthistory',
            old_name='fertilizer',
            new_name='fertilizer_name',
        ),
    ]
