# Generated by Django 4.1.4 on 2023-09-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0051_weight_fertilizer_weighthistory_fertilizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='car_registration_id',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='car_team_id',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='mill_id',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='scoop_id',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='stone_type_id',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='car_registration_id',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='car_team_id',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='mill_id',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='scoop_id',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='stone_type_id',
        ),
        migrations.AddField(
            model_name='weight',
            name='car_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_car_registration', to='weightapp.basecarregistration'),
        ),
        migrations.AddField(
            model_name='weight',
            name='car_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_car_team', to='weightapp.basecarteam'),
        ),
        migrations.AddField(
            model_name='weight',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_customer', to='weightapp.basecustomer'),
        ),
        migrations.AddField(
            model_name='weight',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_driver', to='weightapp.basedriver'),
        ),
        migrations.AddField(
            model_name='weight',
            name='mill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_mill', to='weightapp.basemill'),
        ),
        migrations.AddField(
            model_name='weight',
            name='scoop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_scoop', to='weightapp.basescoop'),
        ),
        migrations.AddField(
            model_name='weight',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_site', to='weightapp.basesite'),
        ),
        migrations.AddField(
            model_name='weight',
            name='stone_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_stone_type', to='weightapp.basestonetype'),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='car_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_history_car_registration', to='weightapp.basecarregistration'),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='car_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_history_car_team', to='weightapp.basecarteam'),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_history_customer', to='weightapp.basecustomer'),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_history_driver', to='weightapp.basedriver'),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='mill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_history_mill', to='weightapp.basemill'),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='scoop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_history_scoop', to='weightapp.basescoop'),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_history_site', to='weightapp.basesite'),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='stone_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_history_stone_type', to='weightapp.basestonetype'),
        ),
    ]
