# Generated by Django 4.1.4 on 2023-09-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0057_basetest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseTest',
        ),
    ]
