# Generated by Django 4.1.4 on 2023-09-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0061_remove_basesite_base_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesite',
            name='des',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='des'),
        ),
    ]
