# Generated by Django 4.1.4 on 2023-09-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0063_customersite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerSite',
            new_name='BaesCustomerSite',
        ),
        migrations.AlterModelOptions(
            name='baescustomersite',
            options={'ordering': ('id',), 'verbose_name': 'ลูกค้าและหน้างาน', 'verbose_name_plural': 'ข้อมูลลูกค้าและหน้างาน'},
        ),
        migrations.AlterModelTable(
            name='baescustomersite',
            table='baes_customer_site',
        ),
    ]
