# Generated by Django 4.1.4 on 2023-09-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0065_alter_baescustomersite_customer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaesCustomerSite',
            new_name='BaseCustomerSite',
        ),
    ]
