# Generated by Django 4.1.4 on 2023-09-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0066_rename_baescustomersite_basecustomersite'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basecustomersite',
            table='base_customer_site',
        ),
    ]
