# Generated by Django 4.1.4 on 2023-10-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0077_basecompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseCompany',
        ),
    ]
