# Generated by Django 4.1.4 on 2023-10-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0091_alter_basecustomer_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesite',
            name='base_site_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อปลายทาง'),
        ),
    ]
