# Generated by Django 4.1.4 on 2023-10-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0093_alter_basejobtype_base_job_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecustomer',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อลูกค้า'),
        ),
    ]
