# Generated by Django 4.1.4 on 2023-10-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0099_alter_basedriver_driver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='exp_bill',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='exp_change',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='exp_note',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='exp_remission',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='exp_type',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='exp_bill',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='exp_change',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='exp_note',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='exp_remission',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='exp_type',
        ),
    ]
