# Generated by Django 4.1.4 on 2023-10-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0102_userscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='is_cancel',
            field=models.BooleanField(default=False, verbose_name='สถานะยกเลิก'),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='is_cancel',
            field=models.BooleanField(default=False, verbose_name='สถานะยกเลิก'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='is_s',
            field=models.BooleanField(default=False, verbose_name='สถานะ non vat'),
        ),
        migrations.AlterField(
            model_name='weighthistory',
            name='is_s',
            field=models.BooleanField(default=False, verbose_name='สถานะ non vat'),
        ),
    ]
