# Generated by Django 4.1.4 on 2023-10-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0104_rename_base_weight_station_name_weight_bws_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='base_weight_station_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='base_weight_station_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
