# Generated by Django 4.1.4 on 2023-11-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0114_remove_production_mill_remove_productiongoal_mill'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoneestimate',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basesite'),
        ),
    ]
