# Generated by Django 4.1.4 on 2023-11-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0120_productionlossitem_mc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='actual_end_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='actual_start_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='actual_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
