# Generated by Django 4.1.4 on 2023-12-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0121_production_actual_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseVisible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อแท็บการใช้งาน')),
            ],
            options={
                'verbose_name': 'แท็บการใช้งาน',
                'verbose_name_plural': 'ข้อมูลแท็บการใช้งาน',
                'db_table': 'base_visible',
                'ordering': ('id',),
            },
        ),
    ]
