# Generated by Django 4.1.4 on 2024-02-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0141_alter_basesec_unique_together_remove_basesec_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesite',
            name='target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='กำลังการผลิต (Target)'),
        ),
    ]
