# Generated by Django 4.1.4 on 2023-06-20 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseVatType',
            fields=[
                ('base_vat_type_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('base_vat_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('base_vat_type_des', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'base_vat_type',
            },
        ),
        migrations.CreateModel(
            name='BaseWeightStation',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('des', models.CharField(blank=True, max_length=120, null=True)),
                ('weight_id_min', models.IntegerField(blank=True, null=True, verbose_name='id น้อยสุดของตาชั่งนี้')),
                ('weight_id_max', models.IntegerField(blank=True, null=True, verbose_name='id มากสุดของตาชั่งนี้')),
                ('vat_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basevattype')),
            ],
            options={
                'db_table': 'base_weight_station',
            },
        ),
        migrations.CreateModel(
            name='BaseWeightType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'base_weight_type',
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('weight_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('date_in', models.DateField(blank=True, null=True)),
                ('date_out', models.DateField(blank=True, null=True)),
                ('time_in', models.TextField(blank=True, null=True)),
                ('time_out', models.TextField(blank=True, null=True)),
                ('ref_id', models.TextField(blank=True, null=True)),
                ('doc_id', models.TextField(blank=True, null=True)),
                ('car_registration_id', models.TextField(blank=True, null=True)),
                ('car_registration_name', models.TextField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('driver_id', models.TextField(blank=True, null=True)),
                ('driver_name', models.TextField(blank=True, null=True)),
                ('customer_id', models.TextField(blank=True, null=True)),
                ('customer_name', models.TextField(blank=True, null=True)),
                ('site', models.TextField(blank=True, null=True)),
                ('mill_id', models.TextField(blank=True, null=True)),
                ('mill_name', models.TextField(blank=True, null=True)),
                ('stone_type', models.TextField(blank=True, null=True)),
                ('pay', models.TextField(blank=True, null=True)),
                ('scale_id', models.TextField(blank=True, null=True)),
                ('scale_name', models.TextField(blank=True, null=True)),
                ('scoop_id', models.TextField(blank=True, null=True)),
                ('scoop_name', models.TextField(blank=True, null=True)),
                ('approve_id', models.TextField(blank=True, null=True)),
                ('approve_name', models.TextField(blank=True, null=True)),
                ('vat_type', models.TextField(blank=True, null=True)),
                ('stone_color', models.TextField(blank=True, null=True)),
                ('car_team', models.TextField(blank=True, null=True)),
                ('clean', models.TextField(blank=True, null=True)),
                ('transport', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('ship_cost', models.TextField(blank=True, null=True)),
                ('carry_type_name', models.TextField(blank=True, null=True)),
                ('line_type', models.TextField(blank=True, null=True)),
                ('bag_type', models.TextField(blank=True, null=True)),
                ('fertilizer', models.TextField(blank=True, null=True)),
                ('pack_weight', models.TextField(blank=True, null=True)),
                ('price_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('q', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('weight_in', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('weight_out', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('weight_total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('oil_content', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origin_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('origin_q', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('freight_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ton', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sack', models.IntegerField(blank=True, null=True)),
                ('price_up', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_down', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_up_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_down_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('freight_cost_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_weight_station_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.baseweightstation')),
            ],
            options={
                'db_table': 'weight',
            },
        ),
        migrations.AddField(
            model_name='baseweightstation',
            name='weight_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.baseweighttype'),
        ),
    ]
