# Generated by Django 4.1.4 on 2023-06-21 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLossType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'base_loss_type',
            },
        ),
        migrations.CreateModel(
            name='BaseMill',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('line_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'base_mill',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('update', models.DateField(auto_now=True, verbose_name='วันที่อัพเดท')),
                ('goal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('accumulated_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('plan_start_time', models.TimeField(blank=True, null=True)),
                ('plan_end_time', models.TimeField(blank=True, null=True)),
                ('plan_time', models.TimeField(blank=True, null=True)),
                ('run_start_time', models.TimeField(blank=True, null=True)),
                ('run_end_time', models.TimeField(blank=True, null=True)),
                ('run_time', models.TimeField(blank=True, null=True)),
                ('total_loss_time', models.TimeField(blank=True, null=True)),
                ('actual_working_time', models.TimeField(blank=True, null=True)),
                ('production_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('accumulated_production_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('capacity_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('mill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basemill')),
            ],
            options={
                'db_table': 'production',
            },
        ),
        migrations.CreateModel(
            name='ProductionLossItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_time', models.TimeField(blank=True, null=True)),
                ('loss_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.baselosstype')),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.production')),
            ],
            options={
                'db_table': 'production_loss_item',
            },
        ),
    ]
