# Generated by Django 4.1.4 on 2024-02-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
