# Generated by Django 4.1.4 on 2023-06-21 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0002_baselosstype_basemill_production_productionlossitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'base_line_type',
            },
        ),
        migrations.RemoveField(
            model_name='basemill',
            name='line_type',
        ),
        migrations.AlterField(
            model_name='baselosstype',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='basemill',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='production',
            name='line_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.baselinetype'),
        ),
    ]
