# Generated by Django 4.1.4 on 2023-06-21 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0003_baselinetype_remove_basemill_line_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
        ),
    ]
