# Generated by Django 4.1.4 on 2023-06-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0004_alter_production_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baselosstype',
            options={'ordering': ['id']},
        ),
    ]
