# Generated by Django 4.1.4 on 2023-06-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0006_alter_productionlossitem_loss_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='actual_working_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='plan_end_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='plan_start_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='plan_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='run_end_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='run_start_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='run_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='total_loss_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
