# Generated by Django 4.1.4 on 2023-07-10 02:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0009_alter_production_mile_run_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ผลิต'),
        ),
        migrations.CreateModel(
            name='ProductionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ผลิต')),
                ('ccumulated_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('line_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.baselinetype')),
                ('mill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basemill')),
            ],
            options={
                'db_table': 'production_goal',
            },
        ),
    ]
