# Generated by Django 4.1.4 on 2023-07-14 07:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0015_alter_basecustomer_options_alter_basejobtype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStoneType',
            fields=[
                ('base_stone_type_id', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='รหัสหิน')),
                ('base_stone_type_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อหิน')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='ประเภทหิน')),
                ('cal_q', models.CharField(blank=True, max_length=120, null=True, verbose_name='ค่าคำนวณคิว')),
            ],
            options={
                'verbose_name': 'ชนิดหิน',
                'verbose_name_plural': 'ข้อมูลชนิดหิน',
                'db_table': 'base_stone_type',
            },
        ),
        migrations.CreateModel(
            name='StoneEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง')),
                ('mill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basemill')),
            ],
            options={
                'db_table': 'stone_estimate',
            },
        ),
        migrations.CreateModel(
            name='StoneEstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('se', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.stoneestimate')),
                ('stone_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basestonetype')),
            ],
            options={
                'db_table': 'stone_estimate_item',
            },
        ),
    ]
