# Generated by Django 4.1.4 on 2023-07-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0016_basestonetype_stoneestimate_stoneestimateitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoneestimateitem',
            name='percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
