# Generated by Django 4.1.4 on 2023-07-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0017_alter_stoneestimateitem_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
