# Generated by Django 4.1.4 on 2023-07-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0021_remove_basetimeestimate_time_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetimeestimate',
            name='time_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
