# Generated by Django 4.1.4 on 2023-08-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0024_alter_weight_options_basesite'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStoneColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'base_stone_color',
            },
        ),
    ]
