# Generated by Django 4.1.4 on 2023-08-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0027_alter_weight_amount_alter_weight_amount_vat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='clean',
            new_name='clean_type',
        ),
    ]
