# Generated by Django 4.1.4 on 2023-08-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0028_rename_clean_weight_clean_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='basestonetype',
            name='is_stone_estimate',
            field=models.BooleanField(default=False, verbose_name='ใช้ในการประมาณการณ์หิน'),
        ),
    ]
