# Generated by Django 4.1.4 on 2023-08-09 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weightapp', '0031_rename_stone_type_weight_stone_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('date_in', models.DateField(blank=True, null=True)),
                ('date_out', models.DateField(blank=True, null=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_id', models.CharField(blank=True, max_length=255, null=True)),
                ('car_registration_id', models.CharField(blank=True, max_length=255, null=True)),
                ('car_registration_name', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_id', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('mill_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mill_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stone_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stone_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pay', models.CharField(blank=True, max_length=255, null=True)),
                ('scale_id', models.CharField(blank=True, max_length=255, null=True)),
                ('scale_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scoop_id', models.CharField(blank=True, max_length=255, null=True)),
                ('scoop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('approve_id', models.CharField(blank=True, max_length=255, null=True)),
                ('approve_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vat_type', models.CharField(blank=True, max_length=255, null=True)),
                ('stone_color', models.CharField(blank=True, max_length=255, null=True)),
                ('car_team', models.CharField(blank=True, max_length=255, null=True)),
                ('clean_type', models.CharField(blank=True, max_length=255, null=True)),
                ('transport', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('carry_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('line_type', models.CharField(blank=True, max_length=255, null=True)),
                ('bag_type', models.CharField(blank=True, max_length=255, null=True)),
                ('fertilizer', models.CharField(blank=True, max_length=255, null=True)),
                ('pack_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('price_per_ton', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('q', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('amount_vat', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('weight_in', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True)),
                ('weight_out', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True)),
                ('weight_total', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True)),
                ('oil_content', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('origin_weight', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True)),
                ('origin_q', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('freight_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('ton', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('sack', models.IntegerField(blank=True, default=0, null=True)),
                ('price_up', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('price_down', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('price_up_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('price_down_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('freight_cost_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('weight_id', models.IntegerField(blank=True, null=True)),
                ('base_weight_station_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.baseweightstation')),
                ('user_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL)),
                ('weight_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.weight')),
            ],
            options={
                'db_table': 'weight_history',
                'ordering': ['update'],
            },
        ),
    ]
