# Generated by Django 4.1.4 on 2023-08-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0035_alter_weighthistory_user_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weighthistory',
            options={'ordering': ['-id']},
        ),
    ]
