# Generated by Django 4.1.4 on 2023-08-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0038_basecarregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDriver',
            fields=[
                ('driver_id', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='รหัสผู้ขับ')),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อผู้ขับ')),
            ],
            options={
                'verbose_name': 'ผู้ขับ',
                'verbose_name_plural': 'ข้อมูลผู้ขับ',
                'db_table': 'base_driver',
            },
        ),
    ]
