# Generated by Django 4.1.4 on 2023-08-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0039_basedriver'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseScoop',
            fields=[
                ('scoop_id', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='รหัสผู้ตัก')),
                ('scoop_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อผู้ตัก')),
            ],
            options={
                'verbose_name': 'ผู้ตัก',
                'verbose_name_plural': 'ข้อมูลผู้ตัก',
                'db_table': 'base_scoop',
            },
        ),
    ]
