# Generated by Django 4.1.4 on 2023-08-11 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0040_basescoop'),
    ]

    operations = [
        migrations.CreateModel(
            name='baseCarryType',
            fields=[
                ('base_carry_type_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('base_carry_type_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'base_carry_type',
            },
        ),
        migrations.CreateModel(
            name='baseTransport',
            fields=[
                ('base_transport_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('base_transport_name', models.CharField(blank=True, max_length=255, null=True)),
                ('base_carry_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecarrytype')),
            ],
            options={
                'db_table': 'base_transport',
            },
        ),
    ]
