# Generated by Django 4.1.4 on 2023-08-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0042_basecarteam_basecar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecar',
            options={'verbose_name': 'รถร่วมและทีม', 'verbose_name_plural': 'ข้อมูลรถร่วมและทีม'},
        ),
    ]
