# Generated by Django 4.1.4 on 2023-08-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0046_rename_car_team_weight_car_team_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weighthistory',
            name='car_team',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='site',
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='car_team_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='car_team_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='site_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
