# Generated by Django 4.1.4 on 2023-09-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0047_remove_weighthistory_car_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basemill',
            old_name='id',
            new_name='mill_id',
        ),
        migrations.RenameField(
            model_name='basemill',
            old_name='name',
            new_name='mill_name',
        ),
    ]
