# Generated by Django 4.1.4 on 2023-09-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0052_remove_weight_car_registration_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='fertilizer',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='fertilizer',
        ),
    ]
