# Generated by Django 4.1.4 on 2023-09-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0053_remove_weight_fertilizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='fertilizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_fertilizer', to='weightapp.basefertilizer'),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='fertilizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_history_fertilizer', to='weightapp.basefertilizer'),
        ),
    ]
