# Generated by Django 4.1.4 on 2023-09-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0055_rename_fertilizer_weight_f_fertilizer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='f_fertilizer',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='f_fertilizer',
        ),
    ]
