# Generated by Django 4.1.4 on 2023-09-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0058_delete_basetest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basefertilizer',
            options={'verbose_name': 'ปุ๋ย', 'verbose_name_plural': 'ข้อมูลปุ๋ย'},
        ),
        migrations.AlterField(
            model_name='basefertilizer',
            name='fertilizer_id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='รหัสปุ๋ย'),
        ),
        migrations.AlterField(
            model_name='basefertilizer',
            name='fertilizer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อปุ๋ย'),
        ),
    ]
