# Generated by Django 4.1.4 on 2023-09-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0059_alter_basefertilizer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='is_s',
            field=models.BooleanField(default=False, verbose_name='พิเศษ'),
        ),
    ]
