# Generated by Django 4.1.4 on 2023-09-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0060_weight_is_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basesite',
            name='base_customer',
        ),
    ]
