# Generated by Django 4.1.4 on 2023-09-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0062_basesite_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecustomer')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basesite')),
            ],
            options={
                'verbose_name': 'ลูกค้าและหน้างาน',
                'verbose_name_plural': 'ข้อมูลลูกค้าและหน้างาน',
                'db_table': 'customer_site',
            },
        ),
    ]
