# Generated by Django 4.1.4 on 2023-10-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0068_remove_basesite_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemill',
            name='weight_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.baseweighttype', verbose_name='ประเภทเครื่องชั่ง'),
        ),
        migrations.AddField(
            model_name='basesite',
            name='weight_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.baseweighttype', verbose_name='ประเภทเครื่องชั่ง'),
        ),
    ]
