# Generated by Django 4.1.4 on 2023-10-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0069_basemill_weight_type_basesite_weight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecustomer',
            name='v_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
