# Generated by Django 4.1.4 on 2023-10-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0071_basecarteam_v_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecar',
            name='v_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='basecarregistration',
            name='v_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='basecustomersite',
            name='v_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='basedriver',
            name='v_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='basejobtype',
            name='v_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='basemill',
            name='v_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='basescoop',
            name='v_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='basesite',
            name='v_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='basestonetype',
            name='v_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
