# Generated by Django 4.1.4 on 2023-10-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0072_basecar_v_stamp_basecarregistration_v_stamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighthistory',
            name='v_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
