# Generated by Django 4.1.4 on 2023-10-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0074_weight_v_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='exp_bill',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='exp_change',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='exp_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='exp_remission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='exp_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='exp_bill',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='exp_change',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='exp_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='exp_remission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='exp_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='is_s',
            field=models.BooleanField(default=False, verbose_name='สถานะยกเลิก'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='is_s',
            field=models.BooleanField(default=False, verbose_name='สถานะยกเลิก'),
        ),
    ]
