# Generated by Django 4.1.4 on 2023-10-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0075_weight_exp_bill_weight_exp_change_weight_exp_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basemill',
            options={'verbose_name': 'ต้นทาง', 'verbose_name_plural': 'ข้อมูลต้นทาง'},
        ),
        migrations.AlterField(
            model_name='basemill',
            name='mill_id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='รหัสต้นทาง'),
        ),
        migrations.AlterField(
            model_name='basemill',
            name='mill_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อต้นทาง'),
        ),
    ]
