# Generated by Django 4.1.4 on 2023-10-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0078_delete_basecompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('code', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'base_comp',
            },
        ),
    ]
