# Generated by Django 4.1.4 on 2023-10-10 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0079_basecompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='basescoop',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecompany', verbose_name='บริษัท'),
        ),
    ]
