# Generated by Django 4.1.4 on 2023-10-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0081_basecarregistration_company_basedriver_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecompany',
            options={'verbose_name': 'บริษัท', 'verbose_name_plural': 'ข้อมูลบริษัท'},
        ),
        migrations.AlterModelOptions(
            name='basecustomersite',
            options={'ordering': ('id',), 'verbose_name': 'ลูกค้าและปลายทาง', 'verbose_name_plural': 'ข้อมูลลูกค้าและปลายทาง'},
        ),
        migrations.AlterModelOptions(
            name='basesite',
            options={'verbose_name': 'ปลายทาง', 'verbose_name_plural': 'ข้อมูลปลายทาง'},
        ),
        migrations.AlterField(
            model_name='basecompany',
            name='code',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='โค้ดบริษัท'),
        ),
        migrations.AlterField(
            model_name='basecompany',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='ชื่อบริษัท'),
        ),
        migrations.AlterField(
            model_name='basecustomersite',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basesite', verbose_name='ปลายทาง'),
        ),
        migrations.AlterField(
            model_name='basesite',
            name='base_site_id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='รหัสปลายทาง'),
        ),
        migrations.AlterField(
            model_name='basesite',
            name='base_site_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อปลายทาง'),
        ),
        migrations.AlterUniqueTogether(
            name='basecustomersite',
            unique_together={('customer', 'site')},
        ),
    ]
