# Generated by Django 4.1.4 on 2023-10-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0082_alter_basecompany_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecarregistration',
            name='car_registration_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อทะเบียนรถ'),
        ),
        migrations.AlterField(
            model_name='basecarteam',
            name='car_team_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อทีม'),
        ),
        migrations.AlterField(
            model_name='basecustomer',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อลูกค้า'),
        ),
        migrations.AlterField(
            model_name='basedriver',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อผู้ขับ'),
        ),
        migrations.AlterField(
            model_name='basejobtype',
            name='base_job_type_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อประเภทงานของลูกค้า'),
        ),
        migrations.AlterField(
            model_name='basescoop',
            name='scoop_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อผู้ตัก'),
        ),
        migrations.AlterField(
            model_name='basesite',
            name='base_site_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อปลายทาง'),
        ),
        migrations.AlterField(
            model_name='basestonetype',
            name='base_stone_type_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อหิน'),
        ),
    ]
