# Generated by Django 4.1.4 on 2023-10-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0084_alter_basecarregistration_car_registration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecarregistration',
            name='car_registration_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อทะเบียนรถ'),
        ),
    ]
