# Generated by Django 4.1.4 on 2023-10-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0085_alter_basecarregistration_car_registration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecarteam',
            name='car_team_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อทีม'),
        ),
        migrations.AlterField(
            model_name='basecustomer',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อลูกค้า'),
        ),
        migrations.AlterField(
            model_name='basedriver',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อผู้ขับ'),
        ),
        migrations.AlterField(
            model_name='basejobtype',
            name='base_job_type_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อประเภทงานของลูกค้า'),
        ),
        migrations.AlterField(
            model_name='basemill',
            name='mill_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อต้นทาง'),
        ),
        migrations.AlterField(
            model_name='basescoop',
            name='scoop_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อผู้ตัก'),
        ),
        migrations.AlterField(
            model_name='basesite',
            name='base_site_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อปลายทาง'),
        ),
        migrations.AlterField(
            model_name='basestonetype',
            name='base_stone_type_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อหิน'),
        ),
    ]
