# Generated by Django 4.1.4 on 2023-10-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0088_alter_basecarteam_car_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecarteam',
            name='car_team_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อทีม'),
        ),
    ]
