# Generated by Django 4.1.4 on 2023-10-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0092_alter_basesite_base_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basejobtype',
            name='base_job_type_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อประเภทงานของลูกค้า'),
        ),
    ]
