# Generated by Django 4.1.4 on 2023-10-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0095_alter_basemill_mill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basestonetype',
            name='base_stone_type_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อหิน'),
        ),
    ]
