# Generated by Django 4.1.4 on 2023-10-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0096_alter_basestonetype_base_stone_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecarteam',
            name='car_team_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อทีม'),
        ),
    ]
