# Generated by Django 4.1.4 on 2023-10-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0097_alter_basecarteam_car_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basescoop',
            name='scoop_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อผู้ตัก'),
        ),
    ]
