# Generated by Django 4.1.4 on 2023-10-16 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weightapp', '0101_weight_exp_bill_weight_exp_change_weight_exp_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='รหัสผู้ชั่ง')),
                ('scale_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อผู้ชั่ง')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'ผู้ชั่ง',
                'verbose_name_plural': 'ข้อมูลผู้ชั่ง',
            },
        ),
    ]
