# Generated by Django 4.1.4 on 2023-10-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0103_weight_is_cancel_weighthistory_is_cancel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='base_weight_station_name',
            new_name='bws',
        ),
        migrations.RenameField(
            model_name='weighthistory',
            old_name='base_weight_station_name',
            new_name='bws',
        ),
    ]
