# Generated by Django 4.1.4 on 2023-10-21 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weightapp', '0105_weight_base_weight_station_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscale',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
    ]
