# Generated by Django 4.1.4 on 2023-11-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0106_alter_userscale_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecustomer',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='ปิดการใช้งาน'),
        ),
    ]
