# Generated by Django 4.1.4 on 2023-11-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0108_production_site_productiongoal_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='site',
        ),
    ]
