# Generated by Django 4.1.4 on 2023-11-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0109_remove_production_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productiongoal',
            name='site',
        ),
    ]
