# Generated by Django 4.1.4 on 2023-11-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0113_production_site_productiongoal_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='mill',
        ),
        migrations.RemoveField(
            model_name='productiongoal',
            name='mill',
        ),
    ]
