# Generated by Django 4.1.4 on 2023-11-11 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0115_stoneestimate_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetimeestimate',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basesite'),
        ),
    ]
