# Generated by Django 4.1.4 on 2023-11-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0116_basetimeestimate_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetimeestimate',
            name='mill',
        ),
        migrations.RemoveField(
            model_name='stoneestimate',
            name='mill',
        ),
    ]
