# Generated by Django 4.1.4 on 2023-11-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0119_basemachinetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlossitem',
            name='mc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basemachinetype'),
        ),
    ]
