# Generated by Django 4.1.4 on 2024-01-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0125_userprofile_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
    ]
