# Generated by Django 4.1.4 on 2024-01-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0126_remove_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ManyToManyField(to='weightapp.basecompany', verbose_name='การมองเห็นแท็ปบริษัท'),
        ),
    ]
