# Generated by Django 4.1.4 on 2024-02-05 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0127_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecompany', verbose_name='บริษัท'),
        ),
        migrations.AddField(
            model_name='stoneestimate',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecompany', verbose_name='บริษัท'),
        ),
    ]
