# Generated by Django 4.1.4 on 2024-02-12 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0132_alter_basesite_s_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemill',
            name='m_comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecompany', verbose_name='โรงโม่ของบริษัท (ต้นทาง)'),
        ),
        migrations.AddField(
            model_name='basemill',
            name='step',
            field=models.IntegerField(blank=True, null=True, verbose_name='ลำดับโรงโม่ของบริษัท (ต้นทาง)'),
        ),
        migrations.AlterField(
            model_name='basesite',
            name='s_comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecompany', verbose_name='โรงโม่ของบริษัท (ปลายทาง)'),
        ),
        migrations.AlterField(
            model_name='basesite',
            name='step',
            field=models.IntegerField(blank=True, null=True, verbose_name='ลำดับโรงโม่ของบริษัท (ปลายทาง)'),
        ),
    ]
