# Generated by Django 4.1.4 on 2024-02-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0134_basecustomer_company'),
    ]

    '''
    operations = [
        migrations.RemoveField(
            model_name='basecustomer',
            name='company',
        ),
    ]    
    '''

