# Generated by Django 4.1.4 on 2024-02-13 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0135_remove_basecustomer_company'),
    ]
    '''
    operations = [
        migrations.CreateModel(
            name='BaseSEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecompany', verbose_name='บริษัท')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecustomer', verbose_name='ผู้รับเหมา')),
            ],
            options={
                'verbose_name': 'ผู้รับเหมาและบริษัท',
                'verbose_name_plural': 'ข้อมูลผู้รับเหมาและบริษัท',
                'db_table': 'base_SEC',
                'ordering': ('id',),
                'unique_together': {('customer', 'company')},
            },
        ),
    ]    
    '''

