# Generated by Django 4.1.4 on 2024-02-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0136_basesec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseSEC',
        ),
    ]
