# Generated by Django 4.1.4 on 2024-02-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0140_basesec'),
    ]

    '''
    operations = [
        migrations.AlterUniqueTogether(
            name='basesec',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='basesec',
            name='company',
        ),
        migrations.AddField(
            model_name='basesec',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, to='weightapp.basecompany', verbose_name='บริษัท'),
        ),
    ]    
    '''

