# Generated by Django 4.1.4 on 2024-03-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0143_setweightoy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setweightoy',
            options={'verbose_name': 'ตั้งค่าน้ำหนักหินปีก่อน', 'verbose_name_plural': 'ข้อมูลตั้งค่าน้ำหนักหินปีก่อน'},
        ),
    ]
