# Generated by Django 4.1.4 on 2024-03-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0144_alter_setweightoy_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setweightoy',
            name='prod',
        ),
        migrations.AddField(
            model_name='setweightoy',
            name='prod_cap',
            field=models.TextField(blank=True, null=True, verbose_name='ตั้งค่าผลิต วันทำงาน'),
        ),
        migrations.AddField(
            model_name='setweightoy',
            name='prod_hpd',
            field=models.TextField(blank=True, null=True, verbose_name='ตั้งค่าผลิต ชม./วัน'),
        ),
        migrations.AddField(
            model_name='setweightoy',
            name='prod_run',
            field=models.TextField(blank=True, null=True, verbose_name='ตั้งค่าผลิต ชม.โม่'),
        ),
        migrations.AddField(
            model_name='setweightoy',
            name='prod_work',
            field=models.TextField(blank=True, null=True, verbose_name='ตั้งค่าผลิต ตัน/ชม.'),
        ),
    ]
