# Generated by Django 4.1.4 on 2024-05-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0145_remove_setweightoy_prod_setweightoy_prod_cap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEiEi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.TextField(blank=True, null=True, verbose_name='เทสระบบ')),
            ],
        ),
    ]
