# Generated by Django 4.1.4 on 2024-05-14 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0146_testeiei'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetCompStoneTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone', models.TextField(blank=True, null=True, verbose_name='list หินหน้า dashbord')),
                ('comp', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecompany', verbose_name='บริษัท')),
            ],
            options={
                'verbose_name': 'ตั้งค่าบริษัทและชนิดหินหน้า dashbord',
                'verbose_name_plural': 'ข้อมูลตั้งค่าบริษัทและชนิดหินหน้า dashbord',
                'db_table': 'set_company_stone_test',
            },
        ),
    ]
