# Generated by Django 4.1.4 on 2024-05-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0147_setcompstonetest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SetCompStoneTest',
            new_name='SetCompStone',
        ),
        migrations.DeleteModel(
            name='TestEiEi',
        ),
        migrations.AlterModelTable(
            name='setcompstone',
            table='set_company_stone',
        ),
    ]
