# Generated by Django 4.1.4 on 2024-06-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0148_rename_setcompstonetest_setcompstone_delete_testeiei_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetPatternCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('start', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('end', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('pattern', models.CharField(blank=True, max_length=120, null=True, unique=True)),
            ],
            options={
                'db_table': 'set_pattern_code',
            },
        ),
        migrations.AlterField(
            model_name='setcompstone',
            name='stone',
            field=models.TextField(blank=True, null=True, verbose_name='list หินหน้า dashbord ***เรียงตาม id'),
        ),
    ]
