# Generated by Django 4.1.4 on 2024-06-04 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0149_setpatterncode_alter_setcompstone_stone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setpatterncode',
            options={'verbose_name': 'ตั้งค่าแพทเทิร์นรหัส Base', 'verbose_name_plural': 'ข้อมูลตั้งค่าแพทเทิร์นรหัส Base'},
        ),
    ]
