# Generated by Django 4.1.4 on 2024-06-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0150_alter_setpatterncode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='setpatterncode',
            name='wt_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Weight Type Id'),
        ),
        migrations.AlterField(
            model_name='setpatterncode',
            name='end',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='ถึง'),
        ),
        migrations.AlterField(
            model_name='setpatterncode',
            name='m_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Models Name'),
        ),
        migrations.AlterField(
            model_name='setpatterncode',
            name='pattern',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='แพทเทิร์นรหัส'),
        ),
        migrations.AlterField(
            model_name='setpatterncode',
            name='start',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='เริ่มจาก'),
        ),
    ]
