# Generated by Django 4.1.4 on 2024-08-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0153_production_uncontrol_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='basevisible',
            name='step',
            field=models.IntegerField(blank=True, null=True, verbose_name='ลำดับแท็ปการใช้งาน'),
        ),
    ]
