# Generated by Django 4.1.4 on 2024-08-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0154_basevisible_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStockSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='ชื่อที่มาของ stock')),
            ],
            options={
                'verbose_name': 'ที่มาของ stock',
                'verbose_name_plural': 'ข้อมูลที่มาของ stock',
                'db_table': 'base_stock_source',
            },
        ),
    ]
