# Generated by Django 4.1.4 on 2024-08-29 14:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0155_basestocksource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ผลิต')),
                ('update', models.DateField(auto_now=True, verbose_name='วันที่อัพเดท')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecompany', verbose_name='บริษัท')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
