# Generated by Django 4.1.4 on 2024-08-30 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0158_rename_stockstoneb_stockstone_alter_stockstone_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockStoneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='จำนวน stock')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basestocksource', verbose_name='ที่มาของ stock')),
                ('ssn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.stockstone', verbose_name='stock stone')),
            ],
            options={
                'db_table': 'stock_stone_item',
            },
        ),
    ]
