# Generated by Django 4.1.4 on 2024-09-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0159_stockstoneitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='basestocksource',
            name='step',
            field=models.IntegerField(blank=True, null=True, verbose_name='ลำดับ'),
        ),
        migrations.AddField(
            model_name='basestocksource',
            name='symbol',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='เครื่องหมาย (+ หรือ -)'),
        ),
    ]
