# Generated by Django 4.1.4 on 2024-09-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0160_basestocksource_step_basestocksource_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basestocksource',
            name='symbol',
            field=models.CharField(blank=True, choices=[('1', '+'), ('2', '-')], max_length=120, null=True, verbose_name='เครื่องหมาย (+ หรือ -)'),
        ),
    ]
