# Generated by Django 4.1.4 on 2024-09-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0161_alter_basestocksource_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basestocksource',
            name='symbol',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=120, null=True, verbose_name='เครื่องหมาย (+ หรือ -)'),
        ),
    ]
