# Generated by Django 4.1.4 on 2024-09-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0162_alter_basestocksource_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstoneitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='จำนวน stock'),
        ),
    ]
