# Generated by Django 4.1.4 on 2024-09-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0163_alter_stockstoneitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemachinetype',
            name='kind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ประเภทเครื่องจักร'),
        ),
        migrations.AlterField(
            model_name='basemachinetype',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อ'),
        ),
    ]
