# Generated by Django 4.1.4 on 2024-11-06 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0165_alter_basemachinetype_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='approveWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='รายการชั่งวันที่')),
                ('update', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approve', models.BooleanField(default=False, verbose_name='สถานะการตวจสอบ')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecompany', verbose_name='บริษัท')),
            ],
            options={
                'verbose_name': 'ยืนยันการตรวจสอบรายการชั่ง',
                'verbose_name_plural': 'ข้อมูลยืนยันการตรวจสอบรายการชั่ง',
                'db_table': 'approve_weight',
            },
        ),
    ]
