# Generated by Django 4.1.4 on 2024-12-02 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weightapp', '0167_weight_apw'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecar',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='basecar',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง'),
        ),
        migrations.AddField(
            model_name='basecarregistration',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='basecarregistration',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง'),
        ),
        migrations.AddField(
            model_name='basecarteam',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='basecarteam',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง'),
        ),
        migrations.AddField(
            model_name='basecustomer',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='basecustomer',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง'),
        ),
        migrations.AddField(
            model_name='basecustomersite',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='basecustomersite',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง'),
        ),
        migrations.AddField(
            model_name='basedriver',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='basedriver',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง'),
        ),
        migrations.AddField(
            model_name='basejobtype',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='basejobtype',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง'),
        ),
        migrations.AddField(
            model_name='basemill',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='basemill',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง'),
        ),
        migrations.AddField(
            model_name='basescoop',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='basescoop',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง'),
        ),
        migrations.AddField(
            model_name='basesite',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='basesite',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง'),
        ),
        migrations.AddField(
            model_name='basestonetype',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='basestonetype',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง'),
        ),
    ]
