# Generated by Django 4.1.4 on 2024-12-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0171_sumstoneestimate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
