# Generated by Django 4.1.4 on 2024-12-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0172_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumstoneestimate',
            name='se_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.stoneestimateitem', verbose_name='StoneEstimateItem'),
        ),
    ]
