# Generated by Django 4.1.4 on 2024-12-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0173_sumstoneestimate_se_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoneestimateitem',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='sum estimate by stone'),
        ),
    ]
