# Generated by Django 4.1.4 on 2024-12-19 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0174_stoneestimateitem_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStoneEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่')),
                ('site_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='id ปลายทาง')),
                ('stone_type_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='id ชนิดหิน')),
                ('total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='sum estimate by stone of month')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecompany', verbose_name='บริษัท')),
            ],
            options={
                'db_table': 'monthly_stone_estimate',
            },
        ),
        migrations.DeleteModel(
            name='SumStoneEstimate',
        ),
    ]
