# Generated by Django 4.1.4 on 2024-12-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0175_monthlystoneestimate_delete_sumstoneestimate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyStoneEstimate',
        ),
    ]
