# Generated by Django 4.1.4 on 2025-01-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0176_delete_monthlystoneestimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecarteam',
            name='oil_customer_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='รหัสลูกค้าน้ำมัน'),
        ),
    ]
