# Generated by Django 4.1.4 on 2025-01-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0177_basecarteam_oil_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetLineMessaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(blank=True, max_length=120, null=True, verbose_name='user/group ID')),
                ('note', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'ตั้งค่า Line Messaging',
                'verbose_name_plural': 'ข้อมูลตั้งค่า Line Messaging',
                'db_table': 'set_line_messaging',
            },
        ),
    ]
