# Generated by Django 4.1.4 on 2025-01-28 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0178_setlinemessaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง')),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='ราคาต้นทุน')),
                ('sell', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='ราคาขาย')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='รวมต้นทุน * ปริมาณน้ำมัน')),
                ('total_sell', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='รวมราคาขาย * ปริมาณน้ำมัน')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecompany', verbose_name='บริษัท')),
            ],
            options={
                'db_table': 'gas_price',
            },
        ),
    ]
