# Generated by Django 4.1.4 on 2025-01-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0179_gasprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='oil_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='oil_sell',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
