# Generated by Django 4.1.4 on 2025-02-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0180_weight_oil_cost_weight_oil_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMillSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='ชื่อที่มาของต้นทาง')),
            ],
            options={
                'verbose_name': 'ที่มาของต้นทาง',
                'verbose_name_plural': 'ข้อมูลที่มาของต้นทาง',
                'db_table': 'base_mill_source',
            },
        ),
        migrations.AlterModelOptions(
            name='gasprice',
            options={'verbose_name': 'ราคาน้ำมัน', 'verbose_name_plural': 'ข้อมูลราคาน้ำมัน'},
        ),
    ]
