# Generated by Django 4.1.4 on 2025-02-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0181_basemillsource_alter_gasprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemill',
            name='mill_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basemillsource', verbose_name='ที่มาของต้นทาง'),
        ),
    ]
