# Generated by Django 4.1.4 on 2025-05-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0184_stoneestimate_other_stoneestimate_scale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoneestimateitem',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='จำนวนที่ได้ (ตัน)'),
        ),
        migrations.AddField(
            model_name='stoneestimateitem',
            name='qty_site',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='ส่งไปต่อ (ตัน)'),
        ),
        migrations.AddField(
            model_name='stoneestimateitem',
            name='site_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='ส่งไปต่อ (รหัสปลายทาง)'),
        ),
    ]
