# Generated by Django 4.1.4 on 2025-05-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0185_stoneestimateitem_qty_stoneestimateitem_qty_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoneestimate',
            name='is_pass',
            field=models.BooleanField(default=False, verbose_name='สถานะการส่งไปโม่ต่อ'),
        ),
    ]
