# Generated by Django 4.1.4 on 2025-06-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0186_stoneestimate_is_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoneestimateitem',
            name='qty_site',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='ส่งไปต่อ (ตัน) ที่แรก'),
        ),
        migrations.AlterField(
            model_name='stoneestimateitem',
            name='site_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='ส่งไปต่อ (รหัสปลายทาง) ที่แรก'),
        ),
    ]
