# Generated by Django 4.1.4 on 2025-06-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0188_stoneestimateitem_nd_qty_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoneestimateitem',
            name='nd_qty_site',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='ส่งไปต่อ (ตัน) ที่สอง'),
        ),
        migrations.AlterField(
            model_name='stoneestimateitem',
            name='nd_site_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='ส่งไปต่อ (รหัสปลายทาง) ที่สอง'),
        ),
    ]
