# Generated by Django 4.1.4 on 2025-06-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0189_alter_stoneestimateitem_nd_qty_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSiteStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='การจัดเก็บของปลายทาง')),
            ],
            options={
                'verbose_name': 'การจัดเก็บของปลายทาง',
                'verbose_name_plural': 'ข้อมูลการจัดเก็บของปลายทาง',
                'db_table': 'base_site_store',
            },
        ),
    ]
