# Generated by Django 4.1.4 on 2025-06-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0190_basesitestore'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesite',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basesitestore', verbose_name='การจัดเก็บ'),
        ),
    ]
