# Generated by Django 4.1.4 on 2025-06-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0191_basesite_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='ชื่อประเภทธุรกิจ')),
            ],
            options={
                'verbose_name': 'ประเภทธุรกิจ',
                'verbose_name_plural': 'ข้อมูลประเภทธุรกิจ',
                'db_table': 'base_biz',
            },
        ),
    ]
