# Generated by Django 4.1.4 on 2025-06-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0192_basebusiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecompany',
            name='biz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basebusiness', verbose_name='ประเภทธุรกิจ'),
        ),
    ]
