# Generated by Django 4.1.4 on 2025-06-18 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0194_basecompany_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ผลิต')),
                ('update', models.DateField(auto_now=True, verbose_name='วันที่อัพเดท')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecompany', verbose_name='บริษัท')),
            ],
            options={
                'db_table': 'port_stock',
            },
        ),
        migrations.CreateModel(
            name='PortStockStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='รวมทั้งหมด')),
                ('ps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.portstock', verbose_name='port stock')),
                ('stone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basestonetype',to_field='base_stone_type_id', verbose_name='ชนิดหิน')),
            ],
            options={
                'db_table': 'port_stock_stone',
            },
        ),
        migrations.CreateModel(
            name='PortStockStoneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('receive', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('pay', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('cus', models.ForeignKey(blank=True, db_column='cus_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecustomer', to_field='customer_id', verbose_name='ลูกค้า')),
                ('pss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.portstockstone')),
            ],
            options={
                'db_table': 'port_stock_stone_item',
            },
        ),
    ]
