# Generated by Django 4.1.4 on 2025-06-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0195_portstock_portstockstone_portstockstoneitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portstockstoneitem',
            name='cus',
            field=models.ForeignKey(blank=True, db_column='cus_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecustomer', verbose_name='ลูกค้า'),
        ),
    ]
