# Generated by Django 4.1.4 on 2025-06-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0196_alter_portstockstoneitem_cus'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecustomer',
            name='is_port_stock',
            field=models.BooleanField(default=False, verbose_name='ใช้ใน stock หินท่าเรือ'),
        ),
    ]
