# Generated by Django 4.1.4 on 2025-07-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0197_basecustomer_is_port_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='portstockstoneitem',
            name='loss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='portstockstoneitem',
            name='other',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='portstockstoneitem',
            name='sell_cus',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
