# Generated by Django 4.2.24 on 2025-10-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0198_portstockstoneitem_loss_portstockstoneitem_other_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMachineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mile_start', models.IntegerField(blank=True, default=0, null=True)),
                ('mile_end', models.IntegerField(blank=True, default=0, null=True)),
                ('diff_time', models.DurationField(blank=True, null=True)),
                ('mc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basemachinetype')),
                ('pd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.production')),
            ],
            options={
                'db_table': 'production_machine_item',
            },
        ),
    ]
