# Generated by Django 4.2.24 on 2025-10-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0199_productionmachineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionmachineitem',
            name='mile_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='productionmachineitem',
            name='mile_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
