# Generated by Django 4.2.24 on 2025-10-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0200_alter_productionmachineitem_mile_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionmachineitem',
            old_name='pd',
            new_name='production',
        ),
    ]
