# Generated by Django 4.2.24 on 2026-01-08 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0201_rename_pd_productionmachineitem_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseWeightRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='ชื่อ')),
                ('descrip', models.CharField(max_length=255, unique=True, verbose_name='คำอธิบาย')),
                ('rate_min', models.IntegerField(blank=True, null=True, verbose_name='เรทน้ำหนักน้อยที่สุด')),
                ('rate_max', models.IntegerField(blank=True, null=True, verbose_name='เรทน้ำหนักมากที่สุด')),
            ],
            options={
                'verbose_name': 'เรทน้ำหนักตาชั่ง',
                'verbose_name_plural': 'ข้อมูลเรทน้ำหนักตาชั่ง',
                'db_table': 'base_weight_range',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='LoadingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('update', models.DateField(auto_now=True, verbose_name='วันที่อัพเดท')),
                ('date_start_rate', models.DateField(default=django.utils.timezone.now, verbose_name='วันเริ่มใช้เรทราคา')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecompany', verbose_name='บริษัท')),
            ],
            options={
                'db_table': 'loading_rate',
            },
        ),
        migrations.CreateModel(
            name='LoadingRateLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mill_id', models.CharField(max_length=120, verbose_name='รหัสต้นทาง')),
                ('site_id', models.CharField(max_length=120, verbose_name='รหัสปลายทาง')),
                ('Lr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.loadingrate')),
            ],
            options={
                'db_table': 'loading_rate_location',
            },
        ),
        migrations.CreateModel(
            name='LoadingRateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tru_scoop', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ค่าตักรถสิบล้อ')),
                ('tru_shipp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ค่าขนรถสิบล้อ')),
                ('chi_scoop', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ค่าตักรถจีน')),
                ('chi_shipp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ค่าขนรถจีน')),
                ('Lr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.loadingrate')),
                ('Lrl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.loadingratelocation')),
                ('wt_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.baseweightrange', verbose_name='เรทน้ำหนักตาชั่ง')),
            ],
            options={
                'db_table': 'loading_rate_item',
            },
        ),
    ]
