# Generated by Django 4.2.24 on 2026-01-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0202_baseweightrange_loadingrate_loadingratelocation_and_more'),
    ]

'''
    operations = [
        migrations.AddField(
            model_name='loadingrateitem',
            name='amount_chi_scoop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='ยอดเงินค่าตักรถสิบล้อ'),
        ),
        migrations.AddField(
            model_name='loadingrateitem',
            name='amount_chi_shipp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='ยอดเงินค่าตักรถสิบล้อ'),
        ),
        migrations.AddField(
            model_name='loadingrateitem',
            name='amount_tru_scoop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='ยอดเงินค่าตักรถสิบล้อ'),
        ),
        migrations.AddField(
            model_name='loadingrateitem',
            name='amount_tru_shipp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='ยอดเงินค่าตักรถสิบล้อ'),
        ),
    ]
'''
