# Generated by Django 4.2.24 on 2026-01-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0203_loadingrateitem_amount_chi_scoop_and_more'),
    ]
'''
    operations = [
        migrations.RemoveField(
            model_name='loadingrateitem',
            name='amount_chi_scoop',
        ),
        migrations.RemoveField(
            model_name='loadingrateitem',
            name='amount_chi_shipp',
        ),
        migrations.RemoveField(
            model_name='loadingrateitem',
            name='amount_tru_scoop',
        ),
        migrations.RemoveField(
            model_name='loadingrateitem',
            name='amount_tru_shipp',
        ),

    ]
'''
