# Generated by Django 4.2.24 on 2026-01-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0207_loadingratelocation_l_mill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingratelocation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อ'),
        ),
    ]
