# Generated by Django 4.2.24 on 2026-01-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0209_remove_loadingratelocation_l_mill_and_more'),
    ]

'''
    operations = [
        migrations.RemoveField(
            model_name='loadingratelocation',
            name='l_mill',
        ),
        migrations.RemoveField(
            model_name='loadingratelocation',
            name='l_site',
        ),
    ]
'''