# Generated by Django 4.2.24 on 2026-01-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0210_remove_loadingratelocation_l_mill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingRateLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.loadingrate')),
                ('mill', models.ForeignKey(blank=True, db_column='mill_id', max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basemill', verbose_name='รหัสต้นทาง')),
                ('site', models.ForeignKey(blank=True, db_column='site_id', max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basesite', verbose_name='รหัสปลายทาง')),
            ],
            options={
                'db_table': 'loading_rate_loc',
            },
        ),
    ]
