# Generated by Django 4.2.24 on 2026-01-12 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0211_loadingrateloc'),
    ]

    '''
    
    operations = [
        migrations.AlterField(
            model_name='loadingrateloc',
            name='mill',
            field=models.ForeignKey(blank=True, db_column='mill_id', max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basemill', verbose_name='รหัสต้นทาง'),
        ),
        migrations.AlterField(
            model_name='loadingrateloc',
            name='site',
            field=models.ForeignKey(blank=True, db_column='site_id', max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basesite', verbose_name='รหัสปลายทาง'),
        ),
    ]

    '''
