# Generated by Django 4.2.24 on 2026-01-12 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0212_alter_loadingrateloc_mill_alter_loadingrateloc_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadingrateitem',
            name='Lrl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.loadingrateloc'),
        ),
    ]
