# Generated by Django 4.2.24 on 2026-01-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0213_alter_loadingrateitem_lrl_delete_loadingratelocation'),
    ]


    operations = [
        migrations.AlterField(
            model_name='portstockstone',
            name='stone',
            field=models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basestonetype', verbose_name='ชนิดหิน'),
        ),
        migrations.AlterField(
            model_name='portstockstoneitem',
            name='cus',
            field=models.ForeignKey(blank=True, db_column='cus_id', max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecustomer', verbose_name='ลูกค้า'),
        ),
    ]
