# Generated by Django 4.2.24 on 2026-01-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0214_alter_portstockstone_stone_and_more'),
    ]

    '''
    operations = [
        migrations.CreateModel(
            name='BaseSEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ManyToManyField(blank=True, null=True, to='weightapp.basecompany', verbose_name='บริษัท')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecustomer', verbose_name='ผู้รับเหมา')),
            ],
            options={
                'verbose_name': 'ผู้รับเหมาและบริษัท',
                'verbose_name_plural': 'ข้อมูลผู้รับเหมาและบริษัท',
                'db_table': 'base_SEC',
                'ordering': ('id',),
            },
        ),
    ]
    '''
