# Generated by Django 4.2.24 on 2026-01-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0215_basesec'),
    ]
    '''
    operations = [
        migrations.DeleteModel(
            name='LoadingRateLocation',
        ),
    ]
    '''
