# Generated by Django 4.2.24 on 2026-01-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0217_basesec_delete_loadingratelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingRateAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt_tru_scoop', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='ค่าตักรถสิบล้อ')),
                ('amt_tru_shipp', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='ค่าขนรถสิบล้อ')),
                ('amt_chi_scoop', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='ค่าตักรถจีน')),
                ('amt_chi_shipp', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='ค่าขนรถจีน')),
                ('Lr_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.loadingrateitem')),
            ],
            options={
                'db_table': 'loading_rate_amount',
            },
        ),
    ]
