# Generated by Django 4.2.24 on 2026-01-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0218_loadingrateamount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadingRateAmount',
        ),
    ]
