# Generated by Django 4.2.24 on 2026-01-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0219_delete_loadingrateamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseweightrange',
            name='company',
            field=models.ManyToManyField(to='weightapp.basecompany', verbose_name='บริษัท'),
        ),
        migrations.AddIndex(
            model_name='loadingrateitem',
            index=models.Index(fields=['Lrl', 'wt_range'], name='loading_rat_Lrl_id_d62655_idx'),
        ),
        migrations.AddIndex(
            model_name='loadingrateitem',
            index=models.Index(fields=['Lr'], name='loading_rat_Lr_id_75ad2e_idx'),
        ),
    ]
