# Generated by Django 4.2.24 on 2026-01-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0220_baseweightrange_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingrateitem',
            name='bh_chi_scoop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='อัตราค่าตักจากแบ็คโฮ (จีน)'),
        ),
        migrations.AddField(
            model_name='loadingrateitem',
            name='bh_tru_scoop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='อัตราค่าตักจากแบ็คโฮ (สิบล้อ)'),
        ),
        migrations.AlterField(
            model_name='loadingrateitem',
            name='chi_scoop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='อัตราค่าตักจากรถตัก (จีน)'),
        ),
        migrations.AlterField(
            model_name='loadingrateitem',
            name='chi_shipp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ค่อัตราค่าขน/บรรทุก (จีน)'),
        ),
        migrations.AlterField(
            model_name='loadingrateitem',
            name='tru_scoop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='อัตราค่าตักจากรถตัก (สิบล้อ)'),
        ),
        migrations.AlterField(
            model_name='loadingrateitem',
            name='tru_shipp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='อัตราค่าขน/บรรทุก (สิบล้อ)'),
        ),
    ]
