# Generated by Django 4.2.24 on 2026-01-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0221_loadingrateitem_bh_chi_scoop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadingrateitem',
            name='chi_shipp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='อัตราค่าขน/บรรทุก (จีน)'),
        ),
    ]
