# Generated by Django 4.2.24 on 2026-01-30 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0222_alter_loadingrateitem_chi_shipp'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingrateloc',
            name='weight_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.baseweighttype', verbose_name='ประเภทเครื่องชั่ง'),
        ),
    ]
