# Generated by Django 4.2.24 on 2026-03-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0223_loadingrateloc_weight_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseweightrange',
            name='rate_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='เรทน้ำหนักมากที่สุด'),
        ),
        migrations.AlterField(
            model_name='baseweightrange',
            name='rate_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='เรทน้ำหนักน้อยที่สุด'),
        ),
    ]
