# Generated by Django 4.2.24 on 2026-03-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0224_alter_baseweightrange_rate_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoneestimateitem',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=8, null=True, verbose_name='เปอร์เซ็นต์'),
        ),
    ]
