# Generated by Django 4.2.29 on 2026-05-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0225_alter_stoneestimateitem_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('bws', models.CharField(max_length=20, null=True)),
                ('do_id', models.IntegerField()),
                ('do_doc_no', models.CharField(max_length=30, null=True)),
                ('carry_type_name', models.CharField(blank=True, max_length=20, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('weight_q', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit_name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'weight_delivery',
                'indexes': [models.Index(fields=['weight_id', 'bws'], name='weight_deli_weight__a5c024_idx'), models.Index(fields=['weight_id', 'do_doc_no'], name='weight_deli_weight__f0c8da_idx'), models.Index(fields=['weight_id'], name='weight_deli_weight__499eb6_idx')],
            },
        ),
    ]
