# Generated by Django 4.2.29 on 2026-05-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0226_weightdelivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightdelivery',
            old_name='weight_kg',
            new_name='weight_ton',
        ),
    ]
