# Generated by Django 4.2.29 on 2026-05-19 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0227_rename_weight_kg_weightdelivery_weight_ton'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('do_id', models.IntegerField()),
                ('doc_no', models.CharField(max_length=30, null=True)),
                ('car_company_tot', models.IntegerField()),
                ('qty_tot', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit_name', models.CharField(max_length=20, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecompany')),
            ],
            options={
                'db_table': 'delivery_order',
                'indexes': [models.Index(fields=['company', 'doc_no'], name='delivery_or_company_fead0e_idx'), models.Index(fields=['doc_no'], name='delivery_or_doc_no_4601ac_idx')],
            },
        ),
    ]
