# Generated by Django 4.2.29 on 2026-05-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0228_deliveryorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='car_customer_tot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='car_company_tot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
