# Generated by Django 4.2.29 on 2026-05-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0229_deliveryorder_car_customer_tot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='delivery_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='doc_no',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='weightdelivery',
            name='bws',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weightdelivery',
            name='delivery_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='weightdelivery',
            name='do_doc_no',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='weightdelivery',
            name='weight_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['doc_no', 'company', 'delivery_date'], name='delivery_or_doc_no_ac4ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='weightdelivery',
            index=models.Index(fields=['do_doc_no', 'bws', 'delivery_date'], name='weight_deli_do_doc__b8f194_idx'),
        ),
    ]
