# Generated by Django 4.2.29 on 2026-05-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0230_alter_deliveryorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='do_id',
        ),
    ]
