# Generated by Django 4.2.29 on 2026-05-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0231_remove_deliveryorder_do_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='comp_code',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
