# Generated by Django 4.2.29 on 2026-05-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0232_deliveryorder_comp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='car_company',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='car_company_rem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='car_customer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='car_customer_rem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
