# Generated by Django 4.2.29 on 2026-05-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0233_deliveryorder_car_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightdelivery',
            name='is_cancel',
            field=models.BooleanField(default=False, verbose_name='สถานะยกเลิกรายการ'),
        ),
    ]
