# Generated by Django 4.2.29 on 2026-05-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0234_weightdelivery_is_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightdelivery',
            name='comp_code',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
