# Generated by Django 4.2.29 on 2026-05-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0235_weightdelivery_comp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='do_doc_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='do_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='do_doc_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='do_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
