# Generated by Django 4.2.29 on 2026-05-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0236_weight_do_doc_no_weight_do_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='do_id',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='do_id',
        ),
    ]
