# Generated by Django 4.2.29 on 2026-05-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0237_remove_weight_do_id_remove_weighthistory_do_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='v_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weightdelivery',
            name='v_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
