# Generated by Django 4.2.29 on 2026-05-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0238_deliveryorder_v_stamp_weightdelivery_v_stamp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deliveryorder',
            name='delivery_or_company_fead0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryorder',
            name='delivery_or_doc_no_ac4ef2_idx',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='company',
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['doc_no', 'comp_code', 'delivery_date'], name='delivery_or_doc_no_211155_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['comp_code', 'doc_no'], name='delivery_or_comp_co_89a2f2_idx'),
        ),
    ]
