# Generated by Django 4.2.29 on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0239_remove_deliveryorder_delivery_or_company_fead0e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='stone_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weighthistory',
            name='stone_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
