# Generated by Django 4.2.29 on 2026-06-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0240_weight_stone_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='customer_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='customer_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='customer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='product_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='sale_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
