# Generated by Django 4.2.29 on 2026-06-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0241_deliveryorder_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='url api data')),
                ('apiname', models.CharField(blank=True, max_length=255, null=True, verbose_name='api name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='username get api')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='password get api')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='token')),
            ],
            options={
                'verbose_name': 'ตั้งค่า API',
                'verbose_name_plural': 'ข้อมูลตั้งค่า API',
                'db_table': 'base_api',
                'ordering': ('id',),
            },
        ),
    ]
