# Generated by Django 4.2.29 on 2026-06-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0242_baseapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='car_company',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='car_company_rem',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='car_company_tot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='car_customer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='car_customer_rem',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='car_customer_tot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
