# Generated by Django 4.2.29 on 2026-06-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0244_alter_deliveryorder_car_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basestonetype',
            name='inactive',
            field=models.BooleanField(default=False, verbose_name='ปิดการใช้งาน'),
        ),
    ]
