# Generated by Django 4.2.29 on 2026-06-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0245_basestonetype_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='site_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='site_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
