# Generated by Django 4.2.24 on 2026-07-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0246_deliveryorder_site_id_deliveryorder_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='financial_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
