# Generated by Django 4.2.29 on 2026-06-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0247_weight_financial_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightdelivery',
            name='weight_doc_id',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
    ]
