# Generated by Django 4.2.29 on 2026-07-30 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weightapp', '0248_weightdelivery_weight_doc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อเครื่อง')),
                ('from_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='เวอร์ชันเดิม')),
                ('to_version', models.CharField(max_length=20, verbose_name='เวอร์ชันใหม่')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่เช็ค')),
                ('update_applied', models.BooleanField(default=False, verbose_name='อัพเดทสำเร็จ')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weightapp.basecompany', verbose_name='บริษัท')),
            ],
            options={
                'verbose_name': 'ประวัติการอัพเดทเครื่อง',
                'verbose_name_plural': 'ประวัติการอัพเดทเครื่อง',
                'db_table': 'client_update_log',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(default='slcblue', max_length=50, verbose_name='รหัสโปรแกรม')),
                ('version', models.CharField(max_length=20, verbose_name='เวอร์ชัน')),
                ('channel', models.CharField(choices=[('stable', 'Stable'), ('beta', 'Beta')], default='stable', max_length=10, verbose_name='ช่องทาง')),
                ('release_notes', models.TextField(blank=True, null=True, verbose_name='รายละเอียดอัพเดท')),
                ('installer_file', models.FileField(upload_to='releases/%Y/%m/', verbose_name='ไฟล์ติดตั้ง')),
                ('file_hash_sha256', models.CharField(blank=True, max_length=64, null=True, verbose_name='SHA256')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='บังคับอัพเดท')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('released_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ปล่อยเวอร์ชัน')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
            ],
            options={
                'verbose_name': 'เวอร์ชันโปรแกรม',
                'verbose_name_plural': 'ข้อมูลเวอร์ชันโปรแกรม',
                'db_table': 'app_release',
                'ordering': ['-released_at'],
                'unique_together': {('product_code', 'version')},
            },
        ),
    ]
