# Generated by Django 4.2.29 on 2026-07-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0249_clientupdatelog_apprelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprelease',
            name='file_hash_sha256',
            field=models.CharField(default='', max_length=64, verbose_name='SHA256'),
            preserve_default=False,
        ),
    ]
