# Generated by Django 4.2.24 on 2026-07-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0250_stockstone_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='note',
        ),
    ]
