# Generated by Django 4.2.29 on 2026-07-30 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0250_alter_apprelease_file_hash_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientupdatelog',
            name='weight_station',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weightapp.baseweightstation', verbose_name='ตาชั่ง'),
        ),
    ]
