# Generated by Django 4.2.29 on 2026-07-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0251_clientupdatelog_weight_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprelease',
            name='target_weight_stations',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='weightapp.baseweightstation', verbose_name='จำกัดเฉพาะตาชั่ง (ว่าง = ทุกตาชั่ง)'),
        ),
    ]
