# Generated by Django 4.2.29 on 2026-07-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0252_apprelease_target_weight_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprelease',
            name='sql_script',
            field=models.FileField(blank=True, null=True, upload_to='releases/sql/%Y/%m/', verbose_name='สคริปต์ SQL (ถ้ามี)'),
        ),
        migrations.AddField(
            model_name='apprelease',
            name='sql_script_hash_sha256',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='SHA256 ของสคริปต์ SQL'),
        ),
        migrations.AddField(
            model_name='clientupdatelog',
            name='sql_applied',
            field=models.BooleanField(default=False, verbose_name='รันสคริปต์ SQL สำเร็จ'),
        ),
    ]
