# Generated by Django 4.2.29 on 2026-07-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0253_apprelease_sql_script_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprelease',
            name='target_weight_stations',
        ),
    ]
