# Generated by Django 4.2.29 on 2026-08-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0254_remove_apprelease_target_weight_stations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryorder',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='weightdelivery',
            options={'ordering': ['id']},
        ),
    ]
