# Generated by Django 4.2.29 on 2026-08-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0255_add_default_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscale',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รหัสผ่าน'),
        ),
        migrations.AddField(
            model_name='userscale',
            name='permission',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='สิทธิ์การใช้งาน'),
        ),
    ]
