# Generated by Django 4.2.29 on 2026-08-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0256_userscale_password_userscale_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscale',
            name='permission',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('edit_weight', 'edit_weight'), ('sale', 'sale'), ('add_setting', 'add_setting')], max_length=255, null=True, verbose_name='สิทธิ์การใช้งาน'),
        ),
    ]
