# Generated by Django 4.2.29 on 2026-08-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0257_alter_userscale_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscale',
            name='permission',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='สิทธิ์การใช้งาน'),
        ),
    ]
