# Generated by Django 4.2.29 on 2026-08-05 10:18

from django.db import migrations, models
import weightapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0258_alter_userscale_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscale',
            name='permission',
            field=models.CharField(blank=True, default=weightapp.models.default_userscale_permission, max_length=255, null=True, verbose_name='สิทธิ์การใช้งาน'),
        ),
    ]
