# Generated by Django 4.2.29 on 2026-08-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0259_alter_userscale_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscale',
            name='v_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
