# Generated by Django 4.2.29 on 2026-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0260_userscale_v_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientupdatelog',
            name='product_code',
            field=models.CharField(blank=True, default='slcblue', max_length=100, null=True, verbose_name='โปรดักส์'),
        ),
    ]
