# Generated by Django 4.2.29 on 2026-08-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0261_clientupdatelog_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprelease',
            name='product_code',
            field=models.CharField(default='Blue.SLC.W1.IN.Server', max_length=50, verbose_name='รหัสโปรแกรม'),
        ),
        migrations.AlterField(
            model_name='clientupdatelog',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='โปรดักส์'),
        ),
    ]
