# Generated by Django 4.2.29 on 2026-08-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0262_alter_apprelease_product_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientupdatelog',
            name='company',
        ),
    ]
