# Generated by Django 4.2.24 on 2026-08-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0252_portstockstone_note'),
        ('weightapp', '0263_remove_clientupdatelog_company'),
    ]

    operations = [
    ]
