# Generated by Django 4.2.24 on 2026-07-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0263_remove_clientupdatelog_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
    ]
