# Generated by Django 4.2.24 on 2026-08-10 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0264_merge_20260810_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalFreightRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(blank=True, max_length=255, null=True, verbose_name='ต้นทาง')),
                ('destination', models.CharField(blank=True, max_length=255, null=True, verbose_name='ปลายทาง')),
                ('base_fuel_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาน้ำมันฐาน')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ระยะทาง')),
                ('payload_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='น้ำหนักบรรทุก')),
                ('fuel_freight_adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ปรับค่าขนส่งตามน้ำมันที่ใช้ ลิตรละ 1 บาท')),
                ('used_payload_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ใช้น้ำหนักบรรทุกเท่าไหร่')),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาเฉลี่ย')),
            ],
            options={
                'verbose_name': 'อัตราค่าขนส่งไปนอกประเทศ',
                'verbose_name_plural': 'อัตราค่าขนส่งไปนอกประเทศ',
                'db_table': 'international_freight_rate',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InternationalFreightRateLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1, verbose_name='เวอร์ชัน')),
                ('origin', models.CharField(blank=True, max_length=255, null=True, verbose_name='ต้นทาง')),
                ('destination', models.CharField(blank=True, max_length=255, null=True, verbose_name='ปลายทาง')),
                ('base_fuel_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาน้ำมันฐาน')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ระยะทาง')),
                ('payload_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='น้ำหนักบรรทุก')),
                ('fuel_freight_adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ปรับค่าขนส่งตามน้ำมันที่ใช้ ลิตรละ 1 บาท')),
                ('used_payload_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ใช้น้ำหนักบรรทุกเท่าไหร่')),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาเฉลี่ย')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดท')),
                ('international_freight_rate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weightapp.internationalfreightrate', verbose_name='อัตราค่าขนส่งไปนอกประเทศ')),
            ],
        ),
        migrations.CreateModel(
            name='BaseCompanyMapBaseCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='ชื่อ')),
                ('base_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecompany', verbose_name='บริษัท')),
                ('base_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecustomer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'บริษัทลูกค้า',
                'verbose_name_plural': 'ข้อมูลบริษัทลูกค้า',
                'db_table': 'base_company_map_base_customer',
                'ordering': ['id'],
                'unique_together': {('base_company', 'base_customer')},
            },
        ),
    ]
