# Generated by Django 4.2.24 on 2026-07-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0266_remove_stock_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='portstockstone',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
    ]
