# Generated by Django 4.2.24 on 2026-08-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0267_alter_basecompanymapbasecustomer_base_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalfreightrate',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='หมายเหตุ'),
        ),
    ]
