# Generated by Django 4.2.24 on 2026-08-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0268_internationalfreightrate_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalFreightRateTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight_carried', models.CharField(choices=[('แบก นน.', 'แบก นน.'), ('ไม่แบก นน.', 'ไม่แบก นน.'), ('ตาม นน.', 'ตาม นน.'), ('นน. 35.01-40 ตัน', 'นน. 35.01-40 ตัน'), ('นน. 40.01-50 ตันขึ้นไป', 'นน. 40.01-50 ตันขึ้นไป'), ('น้อยกว่าหรือเท่ากับ 35 ตัน', 'น้อยกว่าหรือเท่ากับ 35 ตัน'), ('น้ำหนัก 35.01-50 ตัน', 'น้ำหนัก 35.01-50 ตัน'), ('นน 50 ตันขึ้นไป', 'นน 50 ตันขึ้นไป'), ('นน 40-50 ตัน', 'นน 40-50 ตัน'), ('เหมาเรทเดียว', 'เหมาเรทเดียว')], max_length=50, verbose_name='ประเภทการแบกน้ำหนัก')),
                ('freight_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ค่าขนส่ง')),
                ('discount_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ลดบาท/ตัน')),
                ('freight_rate_per_ton_km', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='ค่าขนส่ง บาท/ตัน/กม.')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('team_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecarteam', verbose_name='ทีมขนส่ง')),
            ],
        ),
    ]
