# Generated by Django 4.2.24 on 2026-08-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0265_internationalfreightrate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='financial_note',
        ),
    ]
