# Generated by Django 4.2.24 on 2026-08-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0269_internationalfreightrateteam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internationalfreightrateteam',
            options={'ordering': ['id'], 'verbose_name': 'อัตราค่าขนส่งไปนอกประเทศ (ทีม)', 'verbose_name_plural': 'อัตราค่าขนส่งไปนอกประเทศ (ทีม)'},
        ),
        migrations.AlterModelTable(
            name='internationalfreightrateteam',
            table='international_freight_rate_team',
        ),
    ]
