# Generated by Django 4.2.24 on 2026-08-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0270_alter_internationalfreightrateteam_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internationalfreightratelog',
            options={'ordering': ['-version'], 'verbose_name': 'ประวัติอัตราค่าขนส่งไปนอกประเทศ', 'verbose_name_plural': 'ประวัติอัตราค่าขนส่งไปนอกประเทศ'},
        ),
        migrations.AlterModelTable(
            name='internationalfreightratelog',
            table='international_freight_rate_log',
        ),
    ]
