# Generated by Django 4.2.24 on 2026-08-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0272_internationalfreightrateteam_freight_rate_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internationalfreightratelog',
            old_name='international_freight_rate_id',
            new_name='international_freight_rate',
        ),
        migrations.RenameField(
            model_name='internationalfreightrateteam',
            old_name='international_freight_rate_id',
            new_name='international_freight_rate',
        ),
        migrations.RenameField(
            model_name='internationalfreightrateteam',
            old_name='team_id',
            new_name='team',
        ),
    ]
