# Generated by Django 4.2.24 on 2026-08-14 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0279_internationalfreightrate_origin_destination_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarryingweightRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อเรท')),
                ('description', models.CharField(max_length=255, verbose_name='รายละเอียด')),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='น้ำหนักขั้นต่ำ')),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='น้ำหนักสูงสุด')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
            ],
            options={
                'verbose_name': 'ประเภทการแบกน้ำหนัก',
                'verbose_name_plural': 'ประเภทการแบกน้ำหนัก',
                'db_table': 'carryingweight_rate',
            },
        ),
        migrations.AlterField(
            model_name='internationalfreightrateteam',
            name='weight_carried',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.carryingweightrate', verbose_name='ประเภทการแบกน้ำหนัก'),
        ),
    ]
