# Generated by Django 4.2.24 on 2026-08-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0281_alter_basecompanymapbasecustomer_base_company_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='weight',
            index=models.Index(fields=['carry_type_name', 'date', 'bws_id'], name='weight_carry_date_bws_idx'),
        ),
    ]
