# Generated by Django 4.2.24 on 2026-08-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0280_carryingweightrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecompanymapbasecustomer',
            name='base_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecompany', verbose_name='บริษัท'),
        ),
        migrations.AlterField(
            model_name='basecompanymapbasecustomer',
            name='base_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weightapp.basecustomer', verbose_name='ลูกค้า'),
        ),
    ]
