# Generated by Django 4.2.24 on 2026-08-23 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weightapp', '0285_international_freight_rate_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalfreightrate',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='อนุมัติเมื่อ'),
        ),
        migrations.AddField(
            model_name='internationalfreightrate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='international_freight_rates_approved', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ'),
        ),
        migrations.AddField(
            model_name='internationalfreightrate',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ส่งขออนุมัติเมื่อ'),
        ),
        migrations.CreateModel(
            name='InternationalFreightRateApproval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submit', 'ขออนุมัติ'), ('approve', 'อนุมัติ'), ('reject', 'ไม่อนุมัติ')], max_length=20, verbose_name='การกระทำ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='ความเห็น')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เมื่อ')),
                ('international_freight_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='weightapp.internationalfreightrate', verbose_name='ใบอัตราค่าขนส่ง')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='international_freight_rate_approvals', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
            ],
            options={
                'verbose_name': 'การอนุมัติอัตราค่าขนส่งไปนอกประเทศ',
                'verbose_name_plural': 'การอนุมัติอัตราค่าขนส่งไปนอกประเทศ',
                'db_table': 'international_freight_rate_approval',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['international_freight_rate', 'id'], name='ifr_approval_rate_idx')],
            },
        ),
    ]
