# Generated by Django 4.2.24 on 2026-08-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0283_international_freight_rate_fuel_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internationalfreightratefuelprice',
            options={'ordering': ['-month', '-id'], 'verbose_name': 'ราคาน้ำมันเฉลี่ยรายเดือน', 'verbose_name_plural': 'ราคาน้ำมันเฉลี่ยรายเดือน'},
        ),
        migrations.AlterUniqueTogether(
            name='internationalfreightratefuelprice',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='internationalfreightratefuelprice',
            index=models.Index(fields=['international_freight_rate', '-month', '-id'], name='ifr_fuel_rate_month_idx'),
        ),
    ]
