# Generated by Django 4.2.24 on 2026-09-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0290_basecompanymapbasecustomer_oi_soc_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExOEINVD',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('docnum', models.CharField(blank=True, max_length=12, null=True)),
                ('seqnum', models.IntegerField(blank=True, null=True)),
                ('stkcod', models.CharField(blank=True, max_length=20, null=True)),
                ('stkdes', models.CharField(blank=True, max_length=60, null=True)),
                ('ordqty', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('comcod', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Express : รายการในบิลขายเชื่อ',
                'verbose_name_plural': 'Express : รายการในบิลขายเชื่อ',
                'db_table': 'OEINVD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExOEINVH',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('docnum', models.CharField(blank=True, max_length=12, null=True)),
                ('docdate', models.DateField(blank=True, null=True)),
                ('cuscod', models.CharField(blank=True, max_length=10, null=True)),
                ('cusnam', models.CharField(blank=True, max_length=60, null=True)),
                ('comcod', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Express : หัวบิลขายเชื่อ',
                'verbose_name_plural': 'Express : หัวบิลขายเชื่อ',
                'db_table': 'OEINVH',
                'managed': False,
            },
        ),
    ]
