# Generated by Django 4.2.24 on 2026-09-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0293_ifr_fuel_price_daily_by_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecompanymapbasecustomer',
            name='oi_soc_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='โค้ดขายเชื่อบุคคลภายนอก - น้ำมัน'),
        ),
    ]
