# ราคาน้ำมันฐานในสัญญาเป็นช่วง เช่น 30.00 - 30.99 ไม่ใช่ตัวเลขเดียว
# ช่องเดิม base_fuel_price กลายเป็นขอบล่าง และยังเป็นตัวเดียวที่เอาไปคิดเงิน
# (สูตร K ในไฟล์ excel ใช้ขอบล่างเสมอ ตามที่เจ้าของงานกำหนด)
# ใบเก่าที่กรอกเป็นราคาเดียวไว้ ขอบบนจะเป็น null ซึ่งแปลว่า "ไม่ได้ตกลงเป็นช่วง"
# จึงไม่ต้อง backfill อะไร และยอดเงินของใบเก่าไม่เปลี่ยน

# Generated by Django 4.2.24 on 2026-09-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0297_ifr_drop_payload_weight_and_rate_fuel_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalfreightrate',
            name='base_fuel_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาน้ำมันฐาน (ขอบบน)'),
        ),
        migrations.AlterField(
            model_name='internationalfreightrate',
            name='base_fuel_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาน้ำมันฐาน (ขอบล่าง)'),
        ),
    ]
